version: '3.7'
services:
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhaiduce/househunting
    deploy:
      restart_policy:
        condition: none
    secrets:
      - source: pyramid_main_ini
        target: /run/secrets/production.ini
    logging:
      driver: journald
    links:
      - db
    command: ['/usr/local/bin/initialize_dc_house_hunting_db','/run/secrets/production.ini']
