version: '3.7'
services:
  db:
    volumes:
      - type: bind
        source: ./mysql-config-househunting.cnf
        target: /etc/mysql/conf.d/mysql-config-househunting.cnf
secrets:
  storage_key:
    name: storage_key.1
    file: ./integration_test_secrets/storage_key.keyfile
  mysql_root_password:
    name: mysql_root_password.1
    file: ./integration_test_secrets/db_root_pw
  mysql_production_password:
    name: mysql_production_password.1
    file: ./integration_test_secrets/db_app_pw
  pyramid_auth_secret:
    file: ./integration_test_secrets/pyramid_auth_secret
  pyramid_main_ini:
    file: ./integration_test_secrets/integration_test.ini
  mysql_ca:
    file: ./integration_test_secrets/ca.pem
  mysql_cert:
    file: ./integration_test_secrets/server-cert.pem
  mysql_key:
    file: ./integration_test_secrets/server-key.pem
  dhparams:
    file: ./integration_test_secrets/dhparams.pem
  ssl_certificate:
    name: ssl_certificate.1
    file: ./integration_test_secrets/localhost.localdomain.crt
  ssl_certificate_key:
    name: ssl_certificate_key.1
    file: ./integration_test_secrets/localhost.localdomain.key
