version: '3.7'
services:
  integration_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: househunting_integration_test
    secrets:
      - source: pyramid_main_ini
        target: /run/secrets/production.ini
    links:
      - web
