version: '3.7'
services:
  integration_test:
    network_mode: 'host'
    build:
      context: .
      dockerfile: Dockerfile.test
    image: househunting_integration_test
    secrets:
      - source: client_ini
        target: /run/secrets/production.ini
      - source: ssl_certificate
        target: /etc/ssl/localhost.localdomain.crt
      - source: mysql_ca
        target: /etc/ssl/ca.pem
