FROM jhaiduce/househunting

USER root

WORKDIR /test

RUN apt-get -y install curl libmariadb-dev libmariadb-dev-compat

COPY requirements.test.txt /test
RUN pip3 install -r /test/requirements.test.txt

COPY integration_tests.py /test

ENV NAME World

RUN groupadd --system testuser && \
    useradd --system --no-create-home -s /bin/sh -g testuser testuser

USER testuser

CMD ["pytest","/test/integration_tests.py","-s"]
